//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool InjectGitVersion 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("{appName}")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("{branch}, {hash}, {shortHash}")]
[assembly: AssemblyCompany("{company}")]
[assembly: AssemblyProduct("{appName}")]
[assembly: AssemblyCopyright("Copyright © {year}")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]

[assembly: Guid("a77361bb-8b0b-414f-b0b9-e5297ad505ae")]

[assembly: AssemblyVersion("{version}")]
[assembly: AssemblyFileVersion("{version}")]
